info:
  description: |
    Please refer [IoT Public API Authentication](iot-public-api-headers) to know how to get API Key<br/>
    List of public APIs from IoT security:
    1. Link to [Get Device Detail](iot-public-api#operation/device-detail)
    2. Link to [Get Device Inventory](iot-public-api#operation/device-inventory)
    3. Link to [Get Security Alerts](iot-public-api#operation/alert-list)
    4. Link to [Resolve a Security Alert](iot-public-api#operation/alert-resolve)
    4. Link to [Get Vulnerabilities](iot-public-api#operation/vulnerability-list)
    4. Link to [Resolve Vulnerability Instances](iot-public-api#operation/vulnerability-resolve)
  title: IoT Public API Overview
  version: v4.0
  contact: {}
openapi: 3.0.0
servers:
- url: https://{customer-name}.iot.paloaltonetworks.com
tags:
- description: The IoT Public APIs are listed below.
  name: IoT Public API
paths:
  /pub/v4.0/device:
    get:
      description: 'Get a list of device details for the device with the specified MAC address. <br/> <b>Rate limiting<b/>: 60 times per minute'
      operationId: device-detail
      security:
      - X-Key-Id:  []
        X-Access-Key: []
      summary: Device Detail
      tags:
        - IoT Public API
      parameters:
        $ref: 'api/public/deviceDetail.yaml#/parameters'
      responses:
        $ref: 'api/public/deviceDetail.yaml#/responses'

  /pub/v4.0/device/list:
    get:
      description: 'Get a list of all the devices in your IoT Security inventory. <br/> <b>Rate limiting<b/>: 60 times per minute'
      operationId: device-inventory
      security:
      - X-Key-Id:  []
        X-Access-Key: []
      summary: Device Inventory
      tags:
        - IoT Public API
      parameters:
        $ref: 'api/public/deviceList.yaml#/parameters'
      responses:
        $ref: 'api/public/deviceList.yaml#/responses'

  /pub/v4.0/alert/list:
    get:
      description: 'Get a list of security alerts. <br/> <b>Rate limiting<b/>: 60 times per minute'
      operationId: alert-list
      security:
      - X-Key-Id:  []
        X-Access-Key: []
      summary: Security Alerts
      tags:
        - IoT Public API
      parameters:
        $ref: 'api/public/alertList.yaml#/parameters'
      responses:
        $ref: 'api/public/alertList.yaml#/responses'

  /pub/v4.0/alert/update:
    put:
      description: 'Resolve a security alert. <br/> <b>Rate limiting<b/>: 60 times per minute'
      operationId: alert-resolve
      security:
      - X-Key-Id:  []
        X-Access-Key: []
      summary: Resolve a Security Alert
      tags:
        - IoT Public API
      parameters:
        $ref: 'api/public/alertResolve.yaml#/parameters'
      requestBody:
        $ref: 'api/public/alertResolve.yaml#/requestBody'
      responses:
        $ref: 'api/public/alertResolve.yaml#/responses'

  /pub/v4.0/vulnerability/list:
    get:
      description: 'Get a list of security alerts. <br/> <b>Rate limiting<b/>: 60 times per minute'
      operationId: vulnerability-list
      security:
      - X-Key-Id:  []
        X-Access-Key: []
      summary: Vulnerabilities
      tags:
        - IoT Public API
      parameters:
        $ref: 'api/public/vulnerabilityList.yaml#/parameters'
      responses:
        $ref: 'api/public/vulnerabilityList.yaml#/responses'

  /pub/v4.0/vulnerability/update:
    put:
      description: 'Mark one or more instances of a vulnerability as resolved. <br/> <b>Rate limiting<b/>: 60 times per minute'
      operationId: vulnerability-resolve
      security:
      - X-Key-Id:  []
        X-Access-Key: []
      summary: Resolve Vulnerabilty Instances
      tags:
        - IoT Public API
      parameters:
        $ref: 'api/public/vulnerabilityResolve.yaml#/parameters'
      requestBody:
        $ref: 'api/public/vulnerabilityResolve.yaml#/requestBody'
      responses:
        $ref: 'api/public/vulnerabilityResolve.yaml#/responses'

  /pub/v4.0/device/bulkUpdate:
    put:
      description: 'Bulk update devices for DNAC and CISCO Prime integrations.'
      operationId: general-bulk-update
      security:
      - X-Key-Id:  []
        X-Access-Key: []
      summary: Bulk Update Devices - DNAC and CISCO Prime
      tags:
        - IoT Public API
      parameters:
        $ref: 'api/public/bulkUpdate.yaml#/parameters'
      requestBody:
        $ref: 'api/public/bulkUpdate.yaml#/requestBody'
      responses:
        $ref: 'api/public/bulkUpdate.yaml#/responses'

  /pub/v4.0/device/bulkUpdate?updateSource=cisco_wlc:
    put:
      description: 'Bulk update devices for CISCO WLC'
      operationId: cisco-wlc-bulk-update
      security:
      - X-Key-Id:  []
        X-Access-Key: []
      summary: Bulk Update Devices - Cisco WLC
      tags:
        - IoT Public API
      parameters:
        $ref: 'api/public/bulkUpdateCiscoWLC.yaml#/parameters'
      requestBody:
        $ref: 'api/public/bulkUpdateCiscoWLC.yaml#/requestBody'
      responses:
        $ref: 'api/public/bulkUpdateCiscoWLC.yaml#/responses'

  /pub/v4.0/device/bulkUpdate?updateSource=aruba_wlc:
    put:
      description: 'Bulk update devices for Aruba WLC'
      operationId: aruba-wlc-bulk-update
      security:
      - X-Key-Id:  []
        X-Access-Key: []
      summary: Bulk Update Devices - Aruba WLC
      tags:
        - IoT Public API
      parameters:
        $ref: 'api/public/bulkUpdateArubaWLC.yaml#/parameters'
      requestBody:
        $ref: 'api/public/bulkUpdateArubaWLC.yaml#/requestBody'
      responses:
        $ref: 'api/public/bulkUpdateArubaWLC.yaml#/responses'

  /pub/v4.0/device/bulkUpdate?updateSource=snmp:
    put:
      description: 'Bulk update devices for SNMP'
      operationId: snmp-bulk-update
      security:
      - X-Key-Id:  []
        X-Access-Key: []
      summary: Bulk Update Devices - SNMP
      tags:
        - IoT Public API
      parameters:
        $ref: 'api/public/bulkUpdateSNMP.yaml#/parameters'
      requestBody:
        $ref: 'api/public/bulkUpdateSNMP.yaml#/requestBody'
      responses:
        $ref: 'api/public/bulkUpdateSNMP.yaml#/responses'

components:
  securitySchemes:
    $ref: 'components/securitySchemes.yaml#/securitySchemes'