const sidebars = {
    tp: [
      "tp-public-api-overview",
      "tp-public-api-headers",
      "tp-public-api-access-limits",
      "tp-public-api-manage-key",
      "tp-public-api-best-practices",
      {
        type: "category",
        label: "Advanced Threat Prevention API Endpoints",
        items: [
          {
            type: 'autogenerated',
            dirName: 'atp'
          }
        ],
      },
      {
        type: "category",
        label: "Threat Prevention API Endpoints",
        items: [
          {
            type: "autogenerated",
            dirName: "tp"
          }
        ]
      },
    ],
  
    iot: [
      "iot-public-api-headers",
      {
        type: "category",
        label: "IoT Public API",
        items: [
          {
            type: "autogenerated",
            dirName: "iot"
          }
        ]
      },
    ],
  };
  
  module.exports = sidebars;