name: Algolia docsearch scraper

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Run the docsearch scraper
      if: github.repository == 'PaloAltoNetworks/panos.pan.dev' && github.ref == 'refs/heads/master'
      run: |
        while ! [[ $(curl -sH "Authorization: Bearer ${{ secrets.NETLIFY_TOKEN }}" https://api.netlify.com/api/v1/sites/791dfbf1-c6e8-447d-ac4d-220cb8aa7c6f | jq .state) == '"current"' ]]; do sleep 5; echo "waiting for Netlify build to complete..."; done
        docker run --env APPLICATION_ID=${{ secrets.APPLICATION_ID }} --env API_KEY=${{ secrets.API_KEY }} --env CONFIG='${{ secrets.CONFIG }}' algolia/docsearch-scraper
